<a href="https://colab.research.google.com/github/shriramsiva01/cs_sem2_html_proj/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
lst=[1,2,3,4]
np.array(lst)


array([1, 2, 3, 4])

In [2]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.arange(-5,5,2)

array([-5, -3, -1,  1,  3])

In [18]:
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [20]:
np.random.rand(1,5)

array([[0.47584631, 0.56404796, 0.44926115, 0.58000978, 0.22398041]])

In [22]:
np.random.randint(10,50,5)

array([31, 33, 42, 31, 41])

In [23]:
x=np.linspace(4,20)

In [24]:
type(x)

numpy.ndarray

In [27]:
x.shape

(50,)

In [30]:
x.size

50

In [33]:
x[49]

20.0

In [34]:
x[-1]

20.0

In [36]:
x[45:50]

array([18.69387755, 19.02040816, 19.34693878, 19.67346939, 20.        ])

In [40]:
a=np.arange(0,10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [41]:
b=[1,2,3,4,5]

In [45]:
c=np.array(b)
c

array([1, 2, 3, 4, 5])

In [48]:
sum(a)

45

In [49]:
d=c/2
print(d)

[0.5 1.  1.5 2.  2.5]


In [53]:
mat=np.random.rand(5,6)
print(mat)

[[0.60318092 0.36333635 0.10911555 0.48003326 0.85851117 0.2562999 ]
 [0.36249786 0.5703976  0.50874535 0.19170668 0.65451268 0.42127535]
 [0.08808029 0.6039263  0.1406057  0.44961896 0.66518851 0.38182585]
 [0.45566915 0.73791373 0.23367476 0.37867896 0.35763862 0.94440991]
 [0.7708449  0.92909322 0.26812613 0.23709856 0.36743709 0.22919754]]


In [54]:
print(mat[1:])

[[0.36249786 0.5703976  0.50874535 0.19170668 0.65451268 0.42127535]
 [0.08808029 0.6039263  0.1406057  0.44961896 0.66518851 0.38182585]
 [0.45566915 0.73791373 0.23367476 0.37867896 0.35763862 0.94440991]
 [0.7708449  0.92909322 0.26812613 0.23709856 0.36743709 0.22919754]]


In [55]:
print(mat[0:1])

[[0.60318092 0.36333635 0.10911555 0.48003326 0.85851117 0.2562999 ]]


In [56]:
print(mat[:,0:1])

[[0.60318092]
 [0.36249786]
 [0.08808029]
 [0.45566915]
 [0.7708449 ]]


In [57]:
import pandas as pd

In [66]:
df = pd.read_csv('Stock.csv')
df.head()

Stock
Day Open      High      Low       Close     Adj Close  Volume
1   16.77     17.559999 16.73     17.01     16.934999  271700
2   17.1      17.469999 16.950001 17.200001 17.200001  229800
3   17.059999 17.23     16.870001 17.049999 17.049999  146300
4   16.9      17.33     16.9      16.92     16.92      139700

In [67]:
df.describe()

Stock
count       21
unique      21
top     Volume
freq         1